/**
 * @file SensorData.idl
 * @brief DDS IDL definition for sensor data topics.
 *
 * Defines sensor reading messages for telemetry and monitoring.
 */

#include "MessageHeader.idl"

module dds_messages
{

   enum SensorStatus
   {
      SENSOR_UNKNOWN,
      SENSOR_ONLINE,
      SENSOR_OFFLINE,
      SENSOR_ERROR
   };

   @topic
   struct SensorReading
   {
      MessageHeader header;
      @key string<64> sensor_id;
      string<128> sensor_name;
      double value;
      string<32> unit;
      long long timestamp_ms;
      long quality;
      SensorStatus status;
      double latitude;
      double longitude;
      double altitude;
   };

};
