/**
 * @file TrackData.idl
 * @brief DDS IDL definition for track/position topics.
 *
 * Defines track messages for position reporting and situational awareness.
 */

#include "MessageHeader.idl"

module dds_messages
{

   enum TrackClassification
   {
      TRACK_UNKNOWN,
      TRACK_FRIENDLY,
      TRACK_HOSTILE,
      TRACK_NEUTRAL,
      TRACK_PENDING
   };

   @topic
   struct TrackUpdate
   {
      MessageHeader header;
      @key string<64> track_id;
      string<128> track_name;
      double latitude;
      double longitude;
      double altitude;
      double heading;
      double speed;
      TrackClassification classification;
      long long timestamp_ms;
      long update_number;
      double confidence;
   };

};
